import { describe, it, expect } from 'vitest';
import * as toml from '@iarna/toml';
import { generateToml } from '../../generators/starship.js';
import { DEFAULT_STATE, WizardState } from '../../types.js';
import { MODULES } from '../../config/modules.js';
import { PRESETS } from '../../config/presets.js';

const base: WizardState = {
  ...DEFAULT_STATE,
  leftModules: ['directory', 'git_branch'],
  rightModules: ['cmd_duration'],
  hasNerdFont: false,
  colorScheme: 'default',
  characterSymbol: 'arrow',
};

describe('generateToml', () => {
  it('includes format line with left modules and $fill for right modules', () => {
    const toml = generateToml(base);
    expect(toml).toContain('format       = "$directory$git_branch$fill$cmd_duration\\n$character"');
  });

  it('uses $fill to inline right modules instead of right_format', () => {
    const toml = generateToml(base);
    expect(toml).not.toContain('right_format');
    expect(toml).toContain('$fill$cmd_duration');
  });

  it('omits right_format when right modules are empty', () => {
    const toml = generateToml({ ...base, rightModules: [] });
    expect(toml).not.toContain('right_format');
  });

  it('includes [fill] block with space symbol when right modules are present', () => {
    const toml = generateToml(base);
    expect(toml).toContain('[fill]');
    expect(toml).toContain('symbol = " "');
  });

  it('omits [fill] block when right modules are empty', () => {
    const toml = generateToml({ ...base, rightModules: [] });
    expect(toml).not.toContain('[fill]');
  });

  it('uses nerd font symbol for git_branch when hasNerdFont is true', () => {
    const toml = generateToml({ ...base, hasNerdFont: true });
    expect(toml).toContain('symbol = " "');
  });

  it('uses text fallback for git_branch when hasNerdFont is false', () => {
    const toml = generateToml({ ...base, hasNerdFont: false });
    expect(toml).toContain('symbol = "on "');
  });

  it('applies default color scheme to directory', () => {
    const toml = generateToml({ ...base, colorScheme: 'default' });
    expect(toml).toContain('style             = "bold blue"');
  });

  it('applies pastel color scheme to directory', () => {
    const toml = generateToml({ ...base, colorScheme: 'pastel' });
    expect(toml).toContain('style             = "bold cyan"');
  });

  it('applies minimal color scheme to directory', () => {
    const toml = generateToml({ ...base, colorScheme: 'minimal' });
    expect(toml).toContain('style             = "white"');
  });

  it('uses lambda character symbol', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      characterSymbol: 'lambda',
    });
    expect(toml).toContain('[λ](green)');
  });

  it('uses dollar character symbol', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      characterSymbol: 'dollar',
    });
    expect(toml).toContain('[\\$](green)');
  });

  it('does not emit duplicate module blocks when a module appears on both sides', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['directory'],
      rightModules: ['directory'],
    });
    const matches = toml.match(/^\[directory\]/gm);
    expect(matches).toHaveLength(1);
  });

  it('includes the generated-by header comment', () => {
    const toml = generateToml(base);
    expect(toml).toContain('# Generated by ShellConfigurator');
  });

  it('falls back to $character on second line when leftModules is empty', () => {
    const toml = generateToml({ ...base, leftModules: [], rightModules: [] });
    expect(toml).toContain('format       = "\\n$character"');
  });

  it.each(MODULES.map((m) => [m.id, m.label]))('generates a module block for %s (%s)', (id) => {
    const toml = generateToml({ ...base, leftModules: [id], rightModules: [] });
    expect(toml).toContain(`[${id}]`);
  });

  it('generates a character module block', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      rightModules: [],
    });
    expect(toml).toContain('[character]');
    expect(toml).toContain('success_symbol');
    expect(toml).toContain('error_symbol');
  });

  it('does not duplicate character in the format string from module lists', () => {
    const toml = generateToml({ ...base, leftModules: ['character', 'directory'] });
    const occurrences = (toml.match(/format\s*=.*\$character/g) ?? [])[0] ?? '';
    const count = occurrences.match(/\$character/g)?.length ?? 0;
    expect(count).toBe(1);
  });

  it('handles empty leftModules with right modules present', () => {
    const toml = generateToml({ ...base, leftModules: [], rightModules: ['cmd_duration'] });
    expect(toml).toContain('$fill$cmd_duration');
  });

  it('generates parseable TOML for every preset', () => {
    for (const preset of PRESETS) {
      const state: WizardState = {
        ...DEFAULT_STATE,
        leftModules: preset.leftModules ?? ['directory'],
        rightModules: preset.rightModules ?? [],
      };
      const parsed = toml.parse(generateToml(state));
      expect(parsed, `${preset.id} produced invalid TOML`).toBeTruthy();
    }
  });

  it.each(['default', 'pastel', 'minimal'] as const)(
    'generates parseable TOML for the %s color scheme',
    (colorScheme) => {
      const parsed = toml.parse(generateToml({ ...base, colorScheme }));
      expect(parsed).toBeTruthy();
    }
  );

  it.each(['arrow', 'lambda', 'dollar'] as const)(
    'generates parseable TOML for the %s character symbol',
    (characterSymbol) => {
      const parsed = toml.parse(generateToml({ ...base, characterSymbol }));
      expect(parsed).toBeTruthy();
    }
  );

  it('parsed TOML keeps the fill block and format intact', () => {
    const parsed = toml.parse(generateToml(base)) as Record<string, unknown>;
    expect(parsed['format']).toContain('$fill');
    expect(parsed['add_newline']).toBe(true);
    expect(parsed['fill']).toEqual({ symbol: ' ' });
  });
});

describe('modules selected on both sides', () => {
  it('emits a duplicated module only once in the format string', () => {
    const toml = generateToml({
      ...DEFAULT_STATE,
      leftModules: ['directory', 'character'],
      rightModules: ['directory'],
    });

    const formatLine = toml.split('\n').find((l) => l.startsWith('format')) ?? '';
    expect(formatLine.match(/\$directory/g)).toHaveLength(1);
  });

  it('emits one config block per module when a module is on both sides', () => {
    const toml = generateToml({
      ...DEFAULT_STATE,
      leftModules: ['git_branch', 'character'],
      rightModules: ['git_branch'],
    });

    expect(toml.match(/^\[git_branch\]$/gm)).toHaveLength(1);
  });

  it('keeps a right-only module on the right', () => {
    const toml = generateToml({
      ...DEFAULT_STATE,
      leftModules: ['directory', 'character'],
      rightModules: ['cmd_duration'],
    });

    const formatLine = toml.split('\n').find((l) => l.startsWith('format')) ?? '';
    expect(formatLine).toContain('$fill');
    expect(formatLine).toContain('$cmd_duration');
  });

  it('drops the fill when every right module was already on the left', () => {
    const toml = generateToml({
      ...DEFAULT_STATE,
      leftModules: ['directory', 'character'],
      rightModules: ['directory'],
    });

    expect(toml).not.toContain('$fill');
    expect(toml).not.toContain('[fill]');
  });
});
