import { describe, it, expect } from 'vitest';
import * as toml from '@iarna/toml';
import { generateToml } from '../../generators/starship.ts';
import { DEFAULT_STATE, WizardState } from '../../types.ts';
import { MODULES } from '../../config/modules.ts';
import { PRESETS } from '../../config/presets.ts';
import { PALETTES } from '../../config/palettes.ts';

const base: WizardState = {
  ...DEFAULT_STATE,
  leftModules: ['directory', 'git_branch'],
  rightModules: ['cmd_duration'],
  hasNerdFont: false,
  palette: 'default',
  powerline: false,
  characterSymbol: 'arrow',
};

describe('generateToml', () => {
  it('includes format line with left modules and $fill for right modules', () => {
    const toml = generateToml(base);
    expect(toml).toContain('format       = "$directory$git_branch$fill$cmd_duration\\n$character"');
  });

  it('uses $fill to inline right modules instead of right_format', () => {
    const toml = generateToml(base);
    expect(toml).not.toContain('right_format');
    expect(toml).toContain('$fill$cmd_duration');
  });

  it('omits right_format when right modules are empty', () => {
    const toml = generateToml({ ...base, rightModules: [] });
    expect(toml).not.toContain('right_format');
  });

  it('includes [fill] block with space symbol when right modules are present', () => {
    const toml = generateToml(base);
    expect(toml).toContain('[fill]');
    expect(toml).toContain('symbol = " "');
  });

  it('omits [fill] block when right modules are empty', () => {
    const toml = generateToml({ ...base, rightModules: [] });
    expect(toml).not.toContain('[fill]');
  });

  it('uses nerd font symbol for git_branch when hasNerdFont is true', () => {
    const toml = generateToml({ ...base, hasNerdFont: true });
    expect(toml).toContain('symbol = " "');
  });

  it('uses text fallback for git_branch when hasNerdFont is false', () => {
    const toml = generateToml({ ...base, hasNerdFont: false });
    expect(toml).toContain('symbol = "on "');
  });

  it('styles modules by palette colour name and emits the palette table', () => {
    const generated = generateToml({ ...base, palette: 'tokyo-night' });
    expect(generated).toContain('palette      = "tokyo-night"');
    expect(generated).toContain('style  = "bold directory"');
    expect(generated).toContain('[palettes.tokyo-night]');
    expect(generated).toContain('directory      = "#7aa2f7"');
  });

  it('gives each palette its own colours, so no two presets render alike', () => {
    const tokyo = generateToml({ ...base, palette: 'tokyo-night' });
    const gruvbox = generateToml({ ...base, palette: 'gruvbox' });
    expect(tokyo).not.toEqual(gruvbox);
    expect(gruvbox).toContain('directory      = "#83a598"');
  });

  it('uses lambda character symbol', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      characterSymbol: 'lambda',
    });
    expect(toml).toContain('[λ](bold ok)');
  });

  it('uses dollar character symbol', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      characterSymbol: 'dollar',
    });
    expect(toml).toContain('[\\$](bold ok)');
  });

  it('does not emit duplicate module blocks when a module appears on both sides', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['directory'],
      rightModules: ['directory'],
    });
    const matches = toml.match(/^\[directory\]/gm);
    expect(matches).toHaveLength(1);
  });

  it('includes the generated-by header comment', () => {
    const toml = generateToml(base);
    expect(toml).toContain('# Generated by ShellConfigurator');
  });

  it('falls back to $character on second line when leftModules is empty', () => {
    const toml = generateToml({ ...base, leftModules: [], rightModules: [] });
    expect(toml).toContain('format       = "\\n$character"');
  });

  it.each(MODULES.map((m) => [m.id, m.label]))('generates a module block for %s (%s)', (id) => {
    const toml = generateToml({ ...base, leftModules: [id], rightModules: [] });
    expect(toml).toContain(`[${id}]`);
  });

  it('generates a character module block', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      rightModules: [],
    });
    expect(toml).toContain('[character]');
    expect(toml).toContain('success_symbol');
    expect(toml).toContain('error_symbol');
  });

  it('does not duplicate character in the format string from module lists', () => {
    const toml = generateToml({ ...base, leftModules: ['character', 'directory'] });
    const occurrences = (toml.match(/format\s*=.*\$character/g) ?? [])[0] ?? '';
    const count = occurrences.match(/\$character/g)?.length ?? 0;
    expect(count).toBe(1);
  });

  it('handles empty leftModules with right modules present', () => {
    const toml = generateToml({ ...base, leftModules: [], rightModules: ['cmd_duration'] });
    expect(toml).toContain('$fill$cmd_duration');
  });

  it('generates parseable TOML for every preset', () => {
    for (const preset of PRESETS) {
      const state: WizardState = {
        ...DEFAULT_STATE,
        leftModules: preset.leftModules ?? ['directory'],
        rightModules: preset.rightModules ?? [],
      };
      const parsed = toml.parse(generateToml(state));
      expect(parsed, `${preset.id} produced invalid TOML`).toBeTruthy();
    }
  });

  it.each(PALETTES.map((p) => p.id))('generates parseable TOML for the %s palette', (palette) => {
    const parsed = toml.parse(
      generateToml({ ...base, palette: palette as WizardState['palette'] })
    );
    expect(parsed).toBeTruthy();
  });

  it.each(['arrow', 'lambda', 'dollar'] as const)(
    'generates parseable TOML for the %s character symbol',
    (characterSymbol) => {
      const parsed = toml.parse(generateToml({ ...base, characterSymbol }));
      expect(parsed).toBeTruthy();
    }
  );

  it('parsed TOML keeps the fill block and format intact', () => {
    const parsed = toml.parse(generateToml(base)) as Record<string, unknown>;
    expect(parsed['format']).toContain('$fill');
    expect(parsed['add_newline']).toBe(true);
    expect(parsed['fill']).toEqual({ symbol: ' ' });
  });
});

describe('modules selected on both sides', () => {
  it('emits a duplicated module only once in the format string', () => {
    const toml = generateToml({
      ...DEFAULT_STATE,
      leftModules: ['directory', 'character'],
      rightModules: ['directory'],
    });

    const formatLine = toml.split('\n').find((l) => l.startsWith('format')) ?? '';
    expect(formatLine.match(/\$directory/g)).toHaveLength(1);
  });

  it('emits one config block per module when a module is on both sides', () => {
    const toml = generateToml({
      ...DEFAULT_STATE,
      leftModules: ['git_branch', 'character'],
      rightModules: ['git_branch'],
    });

    expect(toml.match(/^\[git_branch\]$/gm)).toHaveLength(1);
  });

  it('keeps a right-only module on the right', () => {
    const toml = generateToml({
      ...DEFAULT_STATE,
      leftModules: ['directory', 'character'],
      rightModules: ['cmd_duration'],
    });

    const formatLine = toml.split('\n').find((l) => l.startsWith('format')) ?? '';
    expect(formatLine).toContain('$fill');
    expect(formatLine).toContain('$cmd_duration');
  });

  it('drops the fill when every right module was already on the left', () => {
    const toml = generateToml({
      ...DEFAULT_STATE,
      leftModules: ['directory', 'character'],
      rightModules: ['directory'],
    });

    expect(toml).not.toContain('$fill');
    expect(toml).not.toContain('[fill]');
  });
});

// The powerline separators the generator emits, spelled as escapes because they
// live in the Nerd Font private use area and do not survive copy-paste intact.
const SEPARATOR_RIGHT = '\ue0b0';
const SEPARATOR_LEFT = '\ue0b2';

describe('powerline segments', () => {
  const powerlineState: WizardState = {
    ...base,
    hasNerdFont: true,
    powerline: true,
    leftModules: ['directory', 'git_branch', 'character'],
    rightModules: ['nodejs', 'cmd_duration'],
  };

  it('styles segments as a foreground on a coloured background', () => {
    const generated = generateToml(powerlineState);
    expect(generated).toContain('style  = "bold fg:fg bg:directory"');
  });

  it('tints each left separator with the next segment’s colour', () => {
    const generated = generateToml(powerlineState);
    expect(generated).toContain(`[${SEPARATOR_RIGHT}](fg:directory bg:git_branch)`);
  });

  it('leaves the outermost separator without a background', () => {
    const generated = generateToml(powerlineState);
    expect(generated).toContain(`[${SEPARATOR_RIGHT}](fg:git_branch)`);
  });

  it('points right-hand separators back at the previous segment', () => {
    const generated = generateToml(powerlineState);
    expect(generated).toContain(`[${SEPARATOR_LEFT}](fg:nodejs)`);
    expect(generated).toContain(`[${SEPARATOR_LEFT}](fg:cmd_duration bg:nodejs)`);
  });

  it('collapses an empty module instead of leaving a blank block', () => {
    const generated = generateToml(powerlineState);
    const formatLines = generated.split('\n').filter((l) => l.startsWith('format ='));
    expect(formatLines.length).toBeGreaterThan(0);
    for (const line of formatLines) {
      expect(line).toMatch(/= "\(.*\)"$/);
    }
  });

  it('never draws the prompt character as a powerline segment', () => {
    const generated = generateToml(powerlineState);
    expect(generated).toContain("success_symbol = '[❯](bold ok)'");
  });

  it('falls back to a plain prompt when there is no Nerd Font for the separators', () => {
    const generated = generateToml({ ...powerlineState, hasNerdFont: false });
    expect(generated).not.toContain(SEPARATOR_RIGHT);
    expect(generated).not.toContain('bg:directory');
    expect(generated).toContain('style  = "bold directory"');
  });
});

describe('presets are visually distinct', () => {
  // The regression this guards: presets used to differ only in which modules they
  // enabled, so "Tokyo Night" and "Gruvbox Rainbow" generated byte-identical
  // colours and the theme names promised something the generator never produced.
  it('generates a different config for every preset', () => {
    const generated = new Map<string, string>();

    for (const preset of PRESETS) {
      const config = generateToml({
        ...DEFAULT_STATE,
        hasNerdFont: true,
        leftModules: preset.leftModules ?? DEFAULT_STATE.leftModules,
        rightModules: preset.rightModules ?? DEFAULT_STATE.rightModules,
        palette: preset.palette,
        powerline: preset.powerline,
      });

      const clash = [...generated.entries()].find(([, other]) => other === config);
      expect(clash?.[0], `${preset.id} generates the same config as ${clash?.[0]}`).toBeUndefined();
      generated.set(preset.id, config);
    }

    expect(generated.size).toBe(PRESETS.length);
  });

  it('gives every preset a palette of its own', () => {
    const palettes = PRESETS.map((p) => p.palette);
    expect(new Set(palettes).size).toBe(PRESETS.length);
  });
});
