import { describe, it, expect } from 'vitest';
import { generateToml } from '../../generators/starship.js';
import { DEFAULT_STATE, WizardState } from '../../types.js';
import { MODULES } from '../../config/modules.js';

const base: WizardState = {
  ...DEFAULT_STATE,
  leftModules: ['directory', 'git_branch'],
  rightModules: ['cmd_duration'],
  hasNerdFont: false,
  colorScheme: 'default',
  characterSymbol: 'arrow',
};

describe('generateToml', () => {
  it('includes format line with left modules', () => {
    const toml = generateToml(base);
    expect(toml).toContain('format       = "$directory$git_branch\\n"');
  });

  it('includes right_format when right modules are set', () => {
    const toml = generateToml(base);
    expect(toml).toContain('right_format = "$cmd_duration"');
  });

  it('omits right_format when right modules are empty', () => {
    const toml = generateToml({ ...base, rightModules: [] });
    expect(toml).not.toContain('right_format');
  });

  it('uses nerd font symbol for git_branch when hasNerdFont is true', () => {
    const toml = generateToml({ ...base, hasNerdFont: true });
    expect(toml).toContain('symbol = " "');
  });

  it('uses text fallback for git_branch when hasNerdFont is false', () => {
    const toml = generateToml({ ...base, hasNerdFont: false });
    expect(toml).toContain('symbol = "on "');
  });

  it('applies default color scheme to directory', () => {
    const toml = generateToml({ ...base, colorScheme: 'default' });
    expect(toml).toContain('style             = "bold blue"');
  });

  it('applies pastel color scheme to directory', () => {
    const toml = generateToml({ ...base, colorScheme: 'pastel' });
    expect(toml).toContain('style             = "bold cyan"');
  });

  it('applies minimal color scheme to directory', () => {
    const toml = generateToml({ ...base, colorScheme: 'minimal' });
    expect(toml).toContain('style             = "white"');
  });

  it('uses lambda character symbol', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      characterSymbol: 'lambda',
    });
    expect(toml).toContain('[λ](green)');
  });

  it('uses dollar character symbol', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      characterSymbol: 'dollar',
    });
    expect(toml).toContain('[\\$](green)');
  });

  it('does not emit duplicate module blocks when a module appears on both sides', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['directory'],
      rightModules: ['directory'],
    });
    const matches = toml.match(/^\[directory\]/gm);
    expect(matches).toHaveLength(1);
  });

  it('includes the generated-by header comment', () => {
    const toml = generateToml(base);
    expect(toml).toContain('# Generated by ShellConfigurator');
  });

  it('falls back to $character format when leftModules is empty', () => {
    const toml = generateToml({ ...base, leftModules: [], rightModules: [] });
    expect(toml).toContain('format       = "$character\\n"');
    expect(toml).not.toContain('format       = "\\n"');
  });

  it.each(MODULES.map((m) => [m.id, m.label]))('generates a module block for %s (%s)', (id) => {
    const toml = generateToml({ ...base, leftModules: [id], rightModules: [] });
    expect(toml).toContain(`[${id}]`);
  });

  it('generates a character module block', () => {
    const toml = generateToml({
      ...base,
      leftModules: ['character'],
      rightModules: [],
    });
    expect(toml).toContain('[character]');
    expect(toml).toContain('success_symbol');
    expect(toml).toContain('error_symbol');
  });
});
