import { WizardState, ColorScheme, CharacterSymbol } from '../types.js';
import type { ModuleId } from '../config/modules.js';

const SYMBOLS: Record<CharacterSymbol, { success: string; error: string }> = {
  arrow: { success: '[❯](green)', error: '[❯](red)' },
  lambda: { success: '[λ](green)', error: '[λ](red)' },
  dollar: { success: '[\\$](green)', error: '[\\$](red)' },
};

const COLOR_STYLES: Record<ColorScheme, { dir: string; branch: string; status: string }> = {
  default: { dir: 'bold blue', branch: 'bold purple', status: 'bold red' },
  pastel: { dir: 'bold cyan', branch: 'bold magenta', status: 'bold yellow' },
  minimal: { dir: 'white', branch: 'white', status: 'red' },
};

function buildFormatString(modules: string[]): string {
  const parts = modules
    .filter((m) => m !== 'character')
    .map((m) => `$${m}`)
    .join('');
  return parts;
}

function moduleBlock(id: ModuleId, state: WizardState): string {
  const { hasNerdFont, colorScheme } = state;
  const c = COLOR_STYLES[colorScheme];

  switch (id) {
    case 'character':
      return `
[character]
success_symbol = '${SYMBOLS[state.characterSymbol].success}'
error_symbol   = '${SYMBOLS[state.characterSymbol].error}'
`.trim();

    case 'directory':
      return `
[directory]
style             = "${c.dir}"
truncation_length = 3
truncate_to_repo  = true
`.trim();

    case 'git_branch':
      return `
[git_branch]
symbol = "${hasNerdFont ? ' ' : 'on '}"
style  = "${c.branch}"
`.trim();

    case 'git_status':
      return `
[git_status]
style     = "${c.status}"
ahead     = "⇡\${count}"
behind    = "⇣\${count}"
diverged  = "⇕⇡\${ahead_count}⇣\${behind_count}"
modified  = "!\${count}"
staged    = "+\${count}"
untracked = "?\${count}"
deleted   = "-\${count}"
`.trim();

    case 'nodejs':
      return `
[nodejs]
symbol   = "${hasNerdFont ? ' ' : 'node '}"
style    = "bold green"
disabled = false
`.trim();

    case 'python':
      return `
[python]
symbol   = "${hasNerdFont ? ' ' : 'py '}"
style    = "bold yellow"
disabled = false
`.trim();

    case 'rust':
      return `
[rust]
symbol   = "${hasNerdFont ? ' ' : 'rs '}"
style    = "bold red"
disabled = false
`.trim();

    case 'docker_context':
      return `
[docker_context]
symbol   = "${hasNerdFont ? '🐳 ' : 'docker:'}"
style    = "bold blue"
disabled = false
`.trim();

    case 'kubernetes':
      return `
[kubernetes]
symbol   = "${hasNerdFont ? '☸ ' : 'k8s:'}"
style    = "bold cyan"
disabled = false
`.trim();

    case 'aws':
      return `
[aws]
symbol   = "${hasNerdFont ? '☁️  ' : 'aws:'}"
style    = "bold yellow"
disabled = false
`.trim();

    case 'time':
      return `
[time]
disabled    = false
time_format = "%H:%M"
style       = "bold white"
`.trim();

    case 'battery':
      return `
[battery]
disabled = false

[[battery.display]]
threshold = 30
style     = "bold red"

[[battery.display]]
threshold = 80
style     = "bold yellow"
`.trim();

    case 'cmd_duration':
      return `
[cmd_duration]
min_time = 2000
style    = "bold yellow"
`.trim();

    case 'username':
      return `
[username]
show_always = false
style_user  = "bold yellow"
style_root  = "bold red"
`.trim();

    case 'hostname':
      return `
[hostname]
ssh_only = true
style    = "bold green"
`.trim();

    case 'jobs':
      return `
[jobs]
symbol    = "${hasNerdFont ? '✦' : '+'}"
style     = "bold blue"
threshold = 1
`.trim();

    default:
      return `
[${id}]
disabled = false
`.trim();
  }
}

export function generateToml(state: WizardState): string {
  const leftFormat = buildFormatString(state.leftModules);
  const rightFormat = buildFormatString(state.rightModules);

  // Use $fill to right-align modules on the same line, then \n$character
  // on a second line. This avoids right_format which shells pin to the
  // cursor line, causing misalignment on two-line prompts.
  const parts = [leftFormat || ''];
  if (rightFormat) {
    parts.push('$fill', rightFormat);
  }
  parts.push('\\n$character');
  const format = parts.filter(Boolean).join('');

  const allModules = [...new Set([...state.leftModules, ...state.rightModules])] as ModuleId[];

  const blocks = allModules.map((id) => moduleBlock(id, state)).join('\n\n');

  const fillBlock = rightFormat ? `\n\n[fill]\nsymbol = " "` : '';

  const lines: string[] = [
    `# Generated by ShellConfigurator`,
    `# https://github.com/shellconfigurator`,
    ``,
    `format       = "${format}"`,
    `add_newline  = true`,
    ``,
    blocks + fillBlock,
  ];

  return lines.join('\n');
}
