import { WizardState, ColorScheme, CharacterSymbol } from '../types.ts';
import { getModule, type ModuleId } from '../config/modules.ts';

const SYMBOLS: Record<CharacterSymbol, { success: string; error: string }> = {
  arrow: { success: '[❯](green)', error: '[❯](red)' },
  lambda: { success: '[λ](green)', error: '[λ](red)' },
  dollar: { success: '[\\$](green)', error: '[\\$](red)' },
};

const COLOR_STYLES: Record<ColorScheme, { dir: string; branch: string; status: string }> = {
  default: { dir: 'bold blue', branch: 'bold purple', status: 'bold red' },
  pastel: { dir: 'bold cyan', branch: 'bold magenta', status: 'bold yellow' },
  minimal: { dir: 'white', branch: 'white', status: 'red' },
};

function buildFormatString(modules: string[]): string {
  const parts = modules
    .filter((m) => m !== 'character')
    .map((m) => `$${m}`)
    .join('');
  return parts;
}

function moduleBlock(id: ModuleId, state: WizardState): string {
  const { hasNerdFont, colorScheme } = state;

  // The character is not a placeable module, so it has no MODULES entry.
  if (id === 'character') {
    return `
[character]
success_symbol = '${SYMBOLS[state.characterSymbol].success}'
error_symbol   = '${SYMBOLS[state.characterSymbol].error}'
`.trim();
  }

  const def = getModule(id);
  if (!def) {
    // Unknown id (malformed state) — emit a harmless enabling stub.
    return `
[${id}]
disabled = false
`.trim();
  }

  return def.toml({ hasNerdFont, style: COLOR_STYLES[colorScheme] });
}

export function generateToml(state: WizardState): string {
  // A module chosen on both sides would otherwise be emitted twice in the format
  // string and render twice in the prompt. The left side wins.
  const leftModules = [...new Set(state.leftModules)];
  const rightModules = [...new Set(state.rightModules)].filter((id) => !leftModules.includes(id));

  const leftFormat = buildFormatString(leftModules);
  const rightFormat = buildFormatString(rightModules);

  // Use $fill to right-align modules on the same line, then \n$character
  // on a second line. This avoids right_format which shells pin to the
  // cursor line, causing misalignment on two-line prompts.
  const parts = [leftFormat || ''];
  if (rightFormat) {
    parts.push('$fill', rightFormat);
  }
  parts.push('\\n$character');
  const format = parts.filter(Boolean).join('');

  const allModules = [...leftModules, ...rightModules];

  const blocks = allModules.map((id) => moduleBlock(id, state)).join('\n\n');

  const fillBlock = rightFormat ? `\n\n[fill]\nsymbol = " "` : '';

  const lines: string[] = [
    `# Generated by ShellConfigurator`,
    `# https://github.com/adrianjiga/ShellConfigurator`,
    ``,
    `format       = "${format}"`,
    `add_newline  = true`,
    ``,
    blocks + fillBlock,
  ];

  return lines.join('\n');
}
